<?php
 $aik =  array (
  'sitename' => '999影院',
  'pcdomain' => 'http://v.0753co.com',
  'title' => '999影院-免VIP抢先观看最新好看的电影和电视剧',
  'keywords' => '999影院,电视直播网站,999影院快播,高清云影视,云点播,免费看视频,湖南卫视直播,80电影网,最新电影天堂免费在线观看',
  'description' => '999影院,热剧快播,最好看的剧情片尽在﻿999影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播',
  'homelink' => '<a href="http://v.0753co.com/" target="_blank"><font color="red">【999影视】</font></a>',
  'icp' => '',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传</br>若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
  'tongji' => '',
  'changyan' => '',
  'youlian' => '<a target="blank" class="gobtn" href="http://mm.cm920.com">920省惠购</a>	',
  'jiekou1' => 'http://j.zz22x.com/jx/?url=',
  'jiekou2' => 'http://api.xfsub.com/index.php?url=',
  'jiekou3' => 'http://api.47ks.com/webcloud/?v=',
  'jiekou4' => 'http://api.nepian.com/ckparse/?url=',
  'jiekou5' => 'http://aikan-tv.com/?url=',
  'jiekou6' => 'http://api.baiyug.cn/vip/?url=',
  'jiekou7' => 'http://jiexi.071811.cc/jx2.php?url=',
  'jiekou8' => 'http://api.wlzhan.com/sudu/?url=',
  'jiekou9' => 'https://api.flvsp.com/?url=',
  'jiekou10' => 'http://api.wlzhan.com/sudu/?url=',
  'admin_name' => 'ad0753v',
  'admin_pass' => 'e96198a5c1b91a8b9a22346735bc94f9',
  'admin_email' => 'syschen@live.com',
  'logo_dh' => '<img src="images/logo.png">',
  'logo_ss' => '<img id="imgsrc" src="images/sologo.png">',
  'movie_ad' => '',
  'tv_ad' => '',
  'zongyi_ad' => '',
  'dongman_ad' => '',
  'bofang_ad' => '<a href="http://mm.cm920.com" target="_blank"><img src="images/ggzm.png" style="width:100%"></a>',
  'jiazai_ad' => '<a href="http://mm.cm920.com" target="_blank"><img src="images/jiazai.png" width="100%"></a>',
  'dbts' => '【点击选择剧集才会播放哦！】',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian1_ad' => '<a class="style02" href="http://mm.cm920.com" target="_blank"><strong>广告赞助--内部优惠卷速查</strong><div class="article-wechats"> </br> <img src="images/qrcode.jpg"></div> </a>',
  'cebian2_ad' => '<a class="style02" href="http://v.0753co.com" target="_blank"><strong>999影院</strong><h2>999影院-免VIP看视频</h2><p>999影院,热剧快播,最好看的剧情片尽在﻿999影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播。</p></a>',
  'cebian3_ad' => '<h3>广告赞助</h3>			
<div class="textwidget"><a href="http://mall.cm920.com" target="_blank"><img src="images/jianzhi.png" width="100%"></a>',
  'cebian4_ad' => '<a class="style01" href="http://info.cm920.com" target="_blank"><strong>生活资讯</strong><h2>更好的生活资讯</h2><p>花点时间阅读，掌握更多时尚的生活资讯，为美好的生活质量打下理论基石。</p></a></div>',
  'top1_ad' => '',
  'top2_ad' => '',
  'top_ad' => '<a href="http://mm.cm920.com/">购物</a>',
  'weixin_ad' => '<img src="images/qrcode.jpg">',
  'end_ad' => '<a href="http://mall.cm920.com/"><span><img src="images/gouwu.png"/>购物</span></a>',
  'hometopnotice' => '',
  'hometopright' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>